consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609066e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609066e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
info:
  version: ""
paths:
  /computing/add/{hash}/{ETH_key}:
    post:
      description: add computing resource
      operationId: ComputingProvider#add
      parameters:
      - description: ETH private key for transaction
        in: path
        name: ETH_key
        required: true
        type: string
      - description: data IPFS address
        in: path
        name: hash
        required: true
        type: string
      produces:
      - application/vnd.goa.error
      - plain/text
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
        "501":
          description: Not Implemented
          schema:
            $ref: '#/definitions/error'
      summary: add ComputingProvider
      tags:
      - ComputingProvider
  /computing/agree/{ETH_key}/{computing_hash}/{contract_hash}/{public_key}:
    post:
      description: agree computing request for request[ID]
      operationId: ComputingProvider#agree
      parameters:
      - description: ETH private key for transaction
        in: path
        name: ETH_key
        required: true
        type: string
      - description: computing resourse hash
        in: path
        name: computing_hash
        required: true
        type: string
      - description: smart contract hash
        in: path
        name: contract_hash
        required: true
        type: string
      - description: ETH public key(Wallet address)
        in: path
        name: public_key
        required: true
        type: string
      produces:
      - application/vnd.goa.error
      - plain/text
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
        "501":
          description: Not Implemented
          schema:
            $ref: '#/definitions/error'
      summary: agree ComputingProvider
      tags:
      - ComputingProvider
  /computing/del/{hash}/{ETH_key}:
    post:
      description: delete computing resource
      operationId: ComputingProvider#del
      parameters:
      - description: ETH private key for transaction
        in: path
        name: ETH_key
        required: true
        type: string
      - description: data IPFS address
        in: path
        name: hash
        required: true
        type: string
      produces:
      - application/vnd.goa.error
      - plain/text
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
        "501":
          description: Not Implemented
          schema:
            $ref: '#/definitions/error'
      summary: del ComputingProvider
      tags:
      - ComputingProvider
  /computing/upload/{res_hash}/{aes_hash}/{ETH_key}/{request_id}:
    post:
      description: upload result hash for [request_id]
      operationId: ComputingProvider#uploadRes
      parameters:
      - description: ETH private key for transaction
        in: path
        name: ETH_key
        required: true
        type: string
      - description: encrypted aes key hash
        in: path
        name: aes_hash
        required: true
        type: string
      - description: ' [request_id]'
        in: path
        name: request_id
        required: true
        type: integer
      - description: encrypted result hash
        in: path
        name: res_hash
        required: true
        type: string
      produces:
      - application/vnd.goa.error
      - plain/text
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
        "501":
          description: Not Implemented
          schema:
            $ref: '#/definitions/error'
      summary: uploadRes ComputingProvider
      tags:
      - ComputingProvider
  /swagger-ui-dist/{filepath}:
    get:
      operationId: swagger-ui-dist#/swagger-ui-dist/*filepath
      parameters:
      - description: Relative file path
        in: path
        name: filepath
        required: true
        type: string
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/error'
      summary: Download swagger-ui-dist/
  /swagger.json:
    get:
      operationId: swagger#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      summary: Download swagger/swagger.json
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
swagger: "2.0"
