// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// unnamed API: Application Resource Href Factories
//
// Command:
// $ goagen
// --design=ComputingProvider/design
// --out=$(GOPATH)\src\ComputingProvider
// --version=v1.3.1

package app
