// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "computingProvider service APIs": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/ZJU-DistributedAI/ComputingProvider/design
// --out=$(GOPATH)/src/github.com/ZJU-DistributedAI/ComputingProvider
// --version=v1.3.1

package app
